# Generated by Django 3.2 on 2021-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
